// Glossary of Mahjong scoring patterns — HK and Chinese Official (MCR)
// English name, Chinese name (Mandarin Pinyin), fan/points value, description, example

export interface GlossaryEntry {
  english: string;
  chinese: string;
  fan: number;
  description: string;
  example?: string;
  category: 'basic' | 'hand' | 'honor' | 'limit' | 'chinese-high' | 'chinese-mid' | 'chinese-low' | 'chinese-1pt' | 'situational';
  /** Which ruleset(s) this pattern belongs to */
  ruleset: ('hk' | 'chinese' | 'blended')[];
  /** MCR point value (if different from fan) */
  mcrPoints?: number;
}

export const GLOSSARY: Record<string, GlossaryEntry> = {
  // ========== HK PATTERNS ==========

  // === BASIC (1 fan) ===
  'Concealed Hand': {
    english: 'Concealed Hand',
    chinese: '門前清 (Mén Qián Qīng)',
    fan: 1,
    description: 'Win with a fully concealed hand — you never claimed another player\'s discard to form a meld (chow, pong, or kong). You must win by claiming another player\'s discard. If you self-draw, that is the separate "Self-Drawn" pattern instead.',
    example: 'All melds formed from tiles you drew yourself, win on a discard.',
    category: 'basic',
    ruleset: ['hk', 'blended', 'chinese'],
    mcrPoints: 2,
  },
  'Self-Drawn': {
    english: 'Self-Drawn',
    chinese: '自摸 (Zì Mō)',
    fan: 1,
    description: 'Win by drawing the winning tile yourself from the wall, rather than claiming another player\'s discard. All three other players pay you (instead of just the discarder).',
    example: 'You draw the final tile that completes your hand from the wall.',
    category: 'basic',
    ruleset: ['hk', 'blended', 'chinese'],
    mcrPoints: 1,
  },
  'All Chows': {
    english: 'All Chows',
    chinese: '平和 (Píng Hé)',
    fan: 1,
    description: 'All four melds are chows (sequences of three consecutive tiles in the same suit), and your pair is not a value tile (not a Dragon, not your Seat Wind, not the Prevailing Wind). The most common basic winning pattern.',
    example: '1-2-3 Bamboo, 4-5-6 Characters, 7-8-9 Dots, 2-3-4 Bamboo + pair of 5 Dots.',
    category: 'hand',
    ruleset: ['hk', 'blended', 'chinese'],
    mcrPoints: 2,
  },
  'Seat Wind': {
    english: 'Seat Wind',
    chinese: '門風 (Mén Fēng)',
    fan: 1,
    description: 'You have a pong (triplet) or kong of your own Seat Wind tile. Your seat is determined by your position at the table — East, South, West, or North.',
    example: 'Sitting East: three East wind tiles = 1 fan.',
    category: 'honor',
    ruleset: ['hk', 'blended', 'chinese'],
    mcrPoints: 2,
  },
  'Prevailing Wind': {
    english: 'Prevailing Wind',
    chinese: '圈風 (Quān Fēng)',
    fan: 1,
    description: 'You have a pong or kong of the Prevailing (Round) Wind. The prevailing wind starts as East and rotates. If the prevailing wind matches your seat wind, you score BOTH this fan and Seat Wind.',
    example: 'East round: three East wind tiles = 1 fan (+ Seat Wind if sitting East).',
    category: 'honor',
    ruleset: ['hk', 'blended'],
  },
  'Prevalent Wind': {
    english: 'Prevalent Wind',
    chinese: '圈風 (Quān Fēng)',
    fan: 1,
    description: 'MCR name for Prevailing Wind. A pong or kong of the round wind. Worth 2 points in MCR.',
    category: 'honor',
    ruleset: ['chinese'],
    mcrPoints: 2,
  },
  'Dragon Pong': {
    english: 'Dragon Pong',
    chinese: '箭刻 (Jiàn Kè)',
    fan: 1,
    description: 'A pong (triplet) or kong of any Dragon tile — Red (中 Zhōng), Green (發 Fā), or White (白 Bái). Each Dragon pong scores independently, so two Dragon pongs = 2 fan (HK) or 4 pts (MCR).',
    example: 'Three Red Dragon tiles (中中中) = 1 fan / 2 pts.',
    category: 'honor',
    ruleset: ['hk', 'blended', 'chinese'],
    mcrPoints: 2,
  },
  'Rob the Kong': {
    english: 'Rob the Kong',
    chinese: '搶槓 (Qiǎng Gàng)',
    fan: 1,
    description: 'Win by claiming a tile that another player uses to extend a melded pong into a kong. When a player adds a fourth tile to an exposed pong, any player who can use that tile to complete a winning hand may "rob" it.',
    example: 'Player adds a 4th East to their exposed pong; you claim it to win.',
    category: 'situational',
    ruleset: ['hk', 'blended'],
  },

  // === MID-TIER (2-5 fan) ===
  'All Pongs': {
    english: 'All Pongs',
    chinese: '對對和 (Duì Duì Hé)',
    fan: 3,
    description: 'All four melds are pongs (triplets) or kongs. No chows (sequences) allowed. Harder than All Chows because you must match three identical tiles four times.',
    example: '1-1-1 Bamboo, 5-5-5 Characters, 9-9-9 Dots, East-East-East + pair.',
    category: 'hand',
    ruleset: ['hk', 'blended', 'chinese'],
    mcrPoints: 6,
  },
  'Half Flush': {
    english: 'Half Flush',
    chinese: '混一色 (Hùn Yī Sè)',
    fan: 3,
    description: 'Your entire hand uses tiles from only ONE numbered suit (Bamboo, Characters, or Dots) PLUS honor tiles (Winds and/or Dragons). No tiles from any other numbered suit.',
    example: '1-2-3, 4-5-6, 7-8-9 Bamboo + East-East-East + 2-2 Bamboo.',
    category: 'hand',
    ruleset: ['hk', 'blended', 'chinese'],
    mcrPoints: 6,
  },
  'Small Three Dragons': {
    english: 'Small Three Dragons',
    chinese: '小三元 (Xiǎo Sān Yuán)',
    fan: 5,
    description: 'Pongs of two different Dragon tiles, plus a pair of the third Dragon. You effectively have all three dragons represented — two as triplets and one as a pair. The two Dragon pongs also score 1 fan each, so this typically yields 5 fan total (3 for Small Three Dragons + 2 for the Dragon pongs).',
    example: 'Red-Red-Red, Green-Green-Green + White-White pair + two other melds.',
    category: 'hand',
    ruleset: ['hk', 'blended'],
  },
  'Small Four Winds': {
    english: 'Small Four Winds',
    chinese: '小四喜 (Xiǎo Sì Xǐ)',
    fan: 6,
    description: 'Pongs of three different Wind tiles, plus a pair of the fourth Wind. All four winds are represented — three as triplets and one as a pair. The scoring Wind pongs also add their individual fan.',
    example: 'East-East-East, South-South-South, West-West-West + North-North pair + 1 meld.',
    category: 'hand',
    ruleset: ['hk', 'blended'],
  },
  'Full Flush': {
    english: 'Full Flush',
    chinese: '清一色 (Qīng Yī Sè)',
    fan: 7,
    description: 'Your entire hand uses tiles from exactly ONE numbered suit — no honor tiles at all. Harder than Half Flush because Winds and Dragons are excluded too. One of the highest non-limit scoring patterns.',
    example: '1-2-3, 4-5-6, 7-8-9, 1-1-1, 5-5 all in Bamboo.',
    category: 'hand',
    ruleset: ['hk', 'blended', 'chinese'],
    mcrPoints: 24,
  },

  // === LIMIT HANDS (10 fan / max payout) ===
  'Thirteen Orphans': {
    english: 'Thirteen Orphans',
    chinese: '十三幺 (Shí Sān Yāo)',
    fan: 10,
    description: 'One of each of the 13 terminal and honor tiles — 1 and 9 of each suit (6 tiles), all 4 Winds, and all 3 Dragons (7 tiles) — plus one duplicate of any of these to form a pair. Total: 14 tiles. A limit hand worth maximum payout.',
    example: '1b 9b 1c 9c 1d 9d East South West North Red Green White + one duplicate.',
    category: 'limit',
    ruleset: ['hk', 'blended', 'chinese'],
    mcrPoints: 88,
  },
  'Nine Gates': {
    english: 'Nine Gates',
    chinese: '九蓮寶燈 (Jiǔ Lián Bǎo Dēng)',
    fan: 10,
    description: 'A concealed hand in a single suit with the specific pattern 1-1-1-2-3-4-5-6-7-8-9-9-9 plus any one additional tile of that same suit. Called "Nine Gates" because the hand can win on any of the 9 tiles in the suit. Extremely rare.',
    example: '1-1-1-2-3-4-5-6-7-8-9-9-9 Bamboo + any Bamboo tile.',
    category: 'limit',
    ruleset: ['hk', 'blended', 'chinese'],
    mcrPoints: 88,
  },
  'All Honors': {
    english: 'All Honors',
    chinese: '字一色 (Zì Yī Sè)',
    fan: 10,
    description: 'Every tile in your hand is an honor tile (Winds or Dragons). No numbered suit tiles at all. Since honors can only form pongs (no sequences), this is always also All Pongs.',
    example: 'East x3, South x3, Red x3, White x3 + North x2.',
    category: 'limit',
    ruleset: ['hk', 'blended', 'chinese'],
    mcrPoints: 64,
  },
  'All Terminals': {
    english: 'All Terminals',
    chinese: '清老頭 (Qīng Lǎo Tóu)',
    fan: 10,
    description: 'Every tile is a terminal (1 or 9 of a suit). No middle tiles (2-8) and no honor tiles. Since terminals can only form pongs (1-1-1 or 9-9-9, no sequences), this also counts as All Pongs.',
    example: '1-1-1 Bamboo, 9-9-9 Bamboo, 1-1-1 Characters, 9-9-9 Dots + 1-1 Dots.',
    category: 'limit',
    ruleset: ['hk', 'blended', 'chinese'],
    mcrPoints: 64,
  },
  'Great Winds': {
    english: 'Great Winds',
    chinese: '大四喜 (Dà Sì Xǐ)',
    fan: 10,
    description: 'Pongs (or kongs) of ALL four Wind tiles — East, South, West, and North. Your pair can be anything. Incredibly rare.',
    example: 'East x3, South x3, West x3, North x3 + any pair.',
    category: 'limit',
    ruleset: ['hk', 'blended'],
  },
  'Great Dragons': {
    english: 'Great Dragons',
    chinese: '大三元 (Dà Sān Yuán)',
    fan: 10,
    description: 'Pongs (or kongs) of ALL three Dragon tiles — Red (中), Green (發), and White (白). Your fourth meld and pair can be anything.',
    example: 'Red x3, Green x3, White x3 + one meld + pair.',
    category: 'limit',
    ruleset: ['hk', 'blended'],
  },
  'All Kongs': {
    english: 'All Kongs',
    chinese: '十八羅漢 (Shí Bā Luó Hàn)',
    fan: 10,
    description: 'All four melds are kongs (four of a kind). Since kongs require 4 tiles each (16) plus a pair (2) = 18 tiles, this hand is enormous and extremely rare. Also called "Eighteen Arhats."',
    example: '1-1-1-1 Bamboo, 5-5-5-5 Characters, 9-9-9-9 Dots, East x4 + pair.',
    category: 'limit',
    ruleset: ['hk', 'blended'],
  },
  'Heavenly Hand': {
    english: 'Heavenly Hand',
    chinese: '天和 (Tiān Hé)',
    fan: 10,
    description: 'The dealer (East) wins immediately with their initial 14-tile deal before anyone takes a turn. The hand must already be complete when first picked up. Astronomically rare.',
    category: 'limit',
    ruleset: ['hk', 'blended'],
  },
  'Earthly Hand': {
    english: 'Earthly Hand',
    chinese: '地和 (Dì Hé)',
    fan: 10,
    description: 'A non-dealer wins on the very first discard of the game (the dealer\'s first discard), or a non-dealer completes their hand on their very first draw.',
    category: 'limit',
    ruleset: ['hk', 'blended'],
  },
  'Four Concealed Pongs': {
    english: 'Four Concealed Pongs',
    chinese: '四暗刻 (Sì Àn Kè)',
    fan: 10,
    description: 'All four melds are pongs that were completed entirely from self-drawn tiles — none were formed by claiming a discard. Must win by self-draw. Combines the difficulty of All Pongs with fully concealed play.',
    example: 'All four pongs formed from self-drawn tiles, win by self-draw.',
    category: 'limit',
    ruleset: ['hk', 'blended', 'chinese'],
    mcrPoints: 64,
  },
  'Mixed Terminals': {
    english: 'Mixed Terminals',
    chinese: '混老頭 (Hùn Lǎo Tóu)',
    fan: 4,
    description: 'Every tile in your hand is either a terminal (1 or 9) or an honor tile (Wind or Dragon). No middle tiles (2-8) allowed. All melds must be pongs of terminals or honors. Less restrictive than All Terminals (which excludes honors) or All Honors (which excludes terminals).',
    example: '1-1-1 Bamboo, 9-9-9 Dots, East x3, Red x3 + 1-1 Characters.',
    category: 'hand',
    ruleset: ['hk', 'blended'],
  },

  // === Composite / informational terms ===
  'Honor Value Hand': {
    english: 'Honor Value Hand',
    chinese: '番子 (Fān Zi)',
    fan: 1,
    description: 'A hand built around pongs of honor tiles (scoring Winds or Dragons). Each Dragon pong and each scoring Wind pong (Seat Wind or Prevailing Wind) gives 1 fan. Combine with Concealed Hand or Self-Drawn to reach the 3-fan minimum.',
    category: 'honor',
    ruleset: ['hk', 'blended'],
  },
  'Value Pair Upgrade': {
    english: 'Value Pair Upgrade',
    chinese: '番子對',
    fan: 0,
    description: 'You have a pair of value tiles (Dragon or scoring Wind) that could become a pong worth 1 fan if you draw the third. Not a scoring pattern itself — a strategic opportunity.',
    category: 'honor',
    ruleset: ['hk', 'blended'],
  },
  'Concealed + Self-Drawn': {
    english: 'Concealed Self-Drawn',
    chinese: '門清自摸 (Mén Qīng Zì Mō)',
    fan: 2,
    description: 'Win with a fully concealed hand by drawing the winning tile yourself. Combines Concealed Hand (1 fan) + Self-Drawn (1 fan) = 2 fan. You still need 1 more fan from another source to reach the 3-fan minimum.',
    category: 'basic',
    ruleset: ['hk', 'blended'],
  },

  // ========== CHINESE OFFICIAL (MCR) PATTERNS ==========

  // === 88 points ===
  'Big Four Winds': {
    english: 'Big Four Winds',
    chinese: '大四喜 (Dà Sì Xǐ)',
    fan: 88,
    description: 'Pongs or kongs of ALL four Wind tiles — East, South, West, and North. The pair can be anything. In MCR, this is worth 88 points (the maximum). HK equivalent: Great Winds.',
    example: 'East x3, South x3, West x3, North x3 + any pair.',
    category: 'chinese-high',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 88,
  },
  'Four Kongs': {
    english: 'Four Kongs',
    chinese: '四槓 (Sì Gàng)',
    fan: 88,
    description: 'All four melds are kongs (four identical tiles declared as a set). 18 tiles total. Extremely rare, requires multiple kong declarations during the hand.',
    example: '1-1-1-1 Bamboo, 5-5-5-5 Characters, 9-9-9-9 Dots, East-East-East-East + pair.',
    category: 'chinese-high',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 88,
  },
  'Seven Shifted Pairs': {
    english: 'Seven Shifted Pairs',
    chinese: '連七對 (Lián Qī Duì)',
    fan: 88,
    description: 'Seven consecutive pairs in a single suit. For example, 1-1-2-2-3-3-4-4-5-5-6-6-7-7 all in Bamboo. A special hand structure (not 4 melds + pair). Extremely rare and beautiful.',
    example: '1122334455667 Bamboo.',
    category: 'chinese-high',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 88,
  },

  // === 64 points ===
  'Little Four Winds': {
    english: 'Little Four Winds',
    chinese: '小四喜 (Xiǎo Sì Xǐ)',
    fan: 64,
    description: 'Pongs of three different Wind tiles, plus a pair of the fourth Wind. All four winds represented. Worth 64 points in MCR, 6 fan in HK.',
    example: 'East x3, South x3, West x3 + North x2 pair + 1 meld.',
    category: 'chinese-high',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 64,
  },
  'Little Three Dragons': {
    english: 'Little Three Dragons',
    chinese: '小三元 (Xiǎo Sān Yuán)',
    fan: 64,
    description: 'Pongs of two different Dragon tiles, plus a pair of the third Dragon. All three dragons represented. Worth 64 points in MCR.',
    example: 'Red x3, Green x3 + White x2 pair + two other melds.',
    category: 'chinese-high',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 64,
  },
  'Pure Terminal Chows': {
    english: 'Pure Terminal Chows',
    chinese: '一色雙龍會 (Yī Sè Shuāng Lóng Huì)',
    fan: 64,
    description: 'Two copies each of 123 and 789 in a single suit, plus a pair of 5 in that suit. Literally "One-Suit Double Dragon." A beautiful symmetric hand. Must be a single suit with no honors.',
    example: '123-123-789-789 Bamboo + 5-5 Bamboo.',
    category: 'chinese-high',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 64,
  },

  // === 48 points ===
  'Quadruple Chow': {
    english: 'Quadruple Chow',
    chinese: '一色四同順 (Yī Sè Sì Tóng Shùn)',
    fan: 48,
    description: 'Four identical chows (same starting number) in one suit. For example, four copies of 2-3-4 Bamboo. Uses all four copies of three consecutive tiles.',
    example: '2-3-4 x4 in Bamboo + any pair.',
    category: 'chinese-high',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 48,
  },
  'Four Pure Shifted Pungs': {
    english: 'Four Pure Shifted Pungs',
    chinese: '一色四步高 (Yī Sè Sì Bù Gāo)',
    fan: 48,
    description: 'Four pongs of consecutive numbers in the same suit. For example, 1-1-1, 2-2-2, 3-3-3, 4-4-4 all in Bamboo. "Stepped up four times in one suit."',
    example: '111-222-333-444 Bamboo + any pair.',
    category: 'chinese-high',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 48,
  },

  // === 32 points ===
  'Four Shifted Chows': {
    english: 'Four Shifted Chows',
    chinese: '一色四步高 (Yī Sè Sì Bù Gāo)',
    fan: 32,
    description: 'Four chows in one suit, each shifted by 1 or 2 from the previous. For example: 1-2-3, 2-3-4, 3-4-5, 4-5-6 (shift by 1) or 1-2-3, 3-4-5, 5-6-7, 7-8-9 (shift by 2).',
    example: '123-234-345-456 Bamboo + pair.',
    category: 'chinese-mid',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 32,
  },
  'Three Kongs': {
    english: 'Three Kongs',
    chinese: '三槓 (Sān Gàng)',
    fan: 32,
    description: 'Three of the four melds are kongs. The fourth meld is a pong or chow. Requires declaring three kongs during the hand.',
    example: '1-1-1-1 Bamboo, 5-5-5-5 Characters, East-East-East-East + one meld + pair.',
    category: 'chinese-mid',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 32,
  },
  'All Terminals and Honors': {
    english: 'All Terminals and Honors',
    chinese: '混老頭 (Hùn Lǎo Tóu)',
    fan: 32,
    description: 'Every tile is either a terminal (1 or 9) or an honor (Wind or Dragon). Must contain both terminals and honors. Same as HK "Mixed Terminals" but worth 32 MCR points.',
    example: '1-1-1 Bamboo, 9-9-9 Dots, East x3, Red x3 + 1-1 Characters.',
    category: 'chinese-mid',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 32,
  },

  // === 24 points ===
  'Seven Pairs': {
    english: 'Seven Pairs',
    chinese: '七對 (Qī Duì)',
    fan: 24,
    description: 'Seven pairs — a special hand structure of 7 distinct pairs instead of 4 melds + pair. Must have exactly 7 different pairs (no quadruples used as two pairs). Worth 24 MCR points. Not valid in standard HK rules.',
    example: '1-1 Bamboo, 3-3 Characters, 5-5 Dots, East-East, Red-Red, 7-7 Bamboo, 9-9 Dots.',
    category: 'chinese-mid',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 24,
  },
  'Greater Honors and Knitted Tiles': {
    english: 'Greater Honors and Knitted Tiles',
    chinese: '全不靠 (Quán Bù Kào)',
    fan: 24,
    description: 'All 7 honor tiles (4 Winds + 3 Dragons) each exactly once, plus 7 suited tiles in a "knitted" pattern — tiles from {1,4,7}, {2,5,8}, and {3,6,9} each assigned to a different suit. No two tiles form a pair or sequence.',
    example: 'East, South, West, North, Red, Green, White + 1b, 4c, 7d, 2c, 5d, 8b, 3d.',
    category: 'chinese-mid',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 24,
  },
  'All Even Pungs': {
    english: 'All Even Pungs',
    chinese: '全雙刻 (Quán Shuāng Kè)',
    fan: 24,
    description: 'All four melds are pongs of even-numbered suit tiles (2, 4, 6, or 8). The pair must also be an even number. No odd tiles, no terminals, no honors.',
    example: '2-2-2 Bamboo, 4-4-4 Characters, 6-6-6 Dots, 8-8-8 Bamboo + 2-2 Dots.',
    category: 'chinese-mid',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 24,
  },
  'Pure Triple Chow': {
    english: 'Pure Triple Chow',
    chinese: '一色三同順 (Yī Sè Sān Tóng Shùn)',
    fan: 24,
    description: 'Three identical chows in one suit. For example, three copies of 2-3-4 Bamboo.',
    example: '2-3-4 x3 in Bamboo + one other meld + pair.',
    category: 'chinese-mid',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 24,
  },
  'Pure Shifted Pungs': {
    english: 'Pure Shifted Pungs',
    chinese: '一色三節高 (Yī Sè Sān Jié Gāo)',
    fan: 24,
    description: 'Three consecutive pongs in one suit (e.g., 1-1-1, 2-2-2, 3-3-3 all in Bamboo). "Three steps up in one suit."',
    example: '111-222-333 Bamboo + one other meld + pair.',
    category: 'chinese-mid',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 24,
  },
  'Upper Tiles': {
    english: 'Upper Tiles',
    chinese: '全大 (Quán Dà)',
    fan: 24,
    description: 'Every tile is a 7, 8, or 9. No tiles numbered 1-6, no honors. The "all big" hand.',
    example: '7-8-9 Bamboo, 7-7-7 Characters, 8-8-8 Dots, 9-9-9 Bamboo + 7-7 Dots.',
    category: 'chinese-mid',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 24,
  },
  'Middle Tiles': {
    english: 'Middle Tiles',
    chinese: '全中 (Quán Zhōng)',
    fan: 24,
    description: 'Every tile is a 4, 5, or 6. No terminals, no honors. The "all middle" hand.',
    example: '4-5-6 Bamboo, 4-4-4 Characters, 5-5-5 Dots, 6-6-6 Bamboo + 4-4 Dots.',
    category: 'chinese-mid',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 24,
  },
  'Lower Tiles': {
    english: 'Lower Tiles',
    chinese: '全小 (Quán Xiǎo)',
    fan: 24,
    description: 'Every tile is a 1, 2, or 3. No tiles numbered 4-9, no honors. The "all small" hand.',
    example: '1-2-3 Bamboo, 1-1-1 Characters, 2-2-2 Dots, 3-3-3 Bamboo + 1-1 Dots.',
    category: 'chinese-mid',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 24,
  },

  // === 16 points ===
  'Pure Straight': {
    english: 'Pure Straight',
    chinese: '清龍 (Qīng Lóng)',
    fan: 16,
    description: 'A complete straight (1-2-3, 4-5-6, 7-8-9) all in one suit. Three chows spanning the full range. "Pure Dragon."',
    example: '123-456-789 Bamboo + one other meld + pair.',
    category: 'chinese-mid',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 16,
  },
  'Three-Suited Terminal Chows': {
    english: 'Three-Suited Terminal Chows',
    chinese: '三色雙龍會 (Sān Sè Shuāng Lóng Huì)',
    fan: 16,
    description: '123 and 789 in two different suits, plus a pair of 5 in the third suit. "Three-Suited Double Dragon." All four melds are terminal chows across two suits.',
    example: '123 Bamboo, 789 Bamboo, 123 Characters, 789 Characters + 5-5 Dots.',
    category: 'chinese-mid',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 16,
  },
  'All Fives': {
    english: 'All Fives',
    chinese: '全帶五 (Quán Dài Wǔ)',
    fan: 16,
    description: 'Every meld AND the pair contains a 5. Chows must include 5 (345, 456, or 567), pongs must be 555, and the pair is 55.',
    example: '3-4-5 Bamboo, 4-5-6 Characters, 5-5-5 Dots, 5-6-7 Bamboo + 5-5 Characters.',
    category: 'chinese-mid',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 16,
  },
  'Triple Pung': {
    english: 'Triple Pung',
    chinese: '三同刻 (Sān Tóng Kè)',
    fan: 16,
    description: 'The same-numbered pong in all three suits. For example, 3-3-3 Bamboo, 3-3-3 Characters, 3-3-3 Dots.',
    example: '333 Bamboo, 333 Characters, 333 Dots + one other meld + pair.',
    category: 'chinese-mid',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 16,
  },
  'Three Concealed Pungs': {
    english: 'Three Concealed Pungs',
    chinese: '三暗刻 (Sān Àn Kè)',
    fan: 16,
    description: 'Three of the four melds are concealed pongs (formed entirely from self-drawn tiles, not from claiming discards). The fourth meld can be anything.',
    example: 'Three pongs from self-drawn tiles + one open meld + pair.',
    category: 'chinese-mid',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 16,
  },

  // === 12 points ===
  'Upper Four': {
    english: 'Upper Four',
    chinese: '大於五 (Dà Yú Wǔ)',
    fan: 12,
    description: 'Every tile is numbered 6, 7, 8, or 9. No tiles 1-5, no honors. "Greater than five."',
    example: '6-7-8 Bamboo, 7-7-7 Characters, 8-8-8 Dots, 9-9-9 Bamboo + 6-6 Dots.',
    category: 'chinese-mid',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 12,
  },
  'Lower Four': {
    english: 'Lower Four',
    chinese: '小於五 (Xiǎo Yú Wǔ)',
    fan: 12,
    description: 'Every tile is numbered 1, 2, 3, or 4. No tiles 5-9, no honors. "Less than five."',
    example: '1-2-3 Bamboo, 1-1-1 Characters, 2-2-2 Dots, 3-4 wait Bamboo + 4-4 Dots.',
    category: 'chinese-mid',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 12,
  },
  'Big Three Winds': {
    english: 'Big Three Winds',
    chinese: '三風刻 (Sān Fēng Kè)',
    fan: 12,
    description: 'Pongs of three different Wind tiles. The fourth meld is not a wind pong. Similar to Little Four Winds but without the fourth wind as a pair.',
    example: 'East x3, South x3, West x3 + one suited meld + non-wind pair.',
    category: 'chinese-mid',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 12,
  },

  // === 8 points ===
  'Mixed Straight': {
    english: 'Mixed Straight',
    chinese: '花龍 (Huā Lóng)',
    fan: 8,
    description: 'A straight spanning 1-9 using three different suits: 123 in one suit, 456 in another, 789 in the third. "Flower Dragon." Each segment is in a different suit.',
    example: '1-2-3 Bamboo, 4-5-6 Characters, 7-8-9 Dots + one other meld + pair.',
    category: 'chinese-mid',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 8,
  },
  'Reversible Tiles': {
    english: 'Reversible Tiles',
    chinese: '推不倒 (Tuī Bù Dǎo)',
    fan: 8,
    description: 'Every tile in the hand looks the same when flipped upside down. Only specific tiles qualify: Bamboo 2,4,5,6,8,9; Dots 1,2,3,4,5,8,9; and White Dragon. "Cannot be pushed over."',
    example: 'Hand using only reversible-symmetric tiles.',
    category: 'chinese-mid',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 8,
  },
  'Mixed Triple Chow': {
    english: 'Mixed Triple Chow',
    chinese: '三色三同順 (Sān Sè Sān Tóng Shùn)',
    fan: 8,
    description: 'The same chow (same starting number) in all three suits. For example, 2-3-4 in Bamboo, Characters, and Dots.',
    example: '2-3-4 Bamboo, 2-3-4 Characters, 2-3-4 Dots + one other meld + pair.',
    category: 'chinese-mid',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 8,
  },
  'Mixed Shifted Pungs': {
    english: 'Mixed Shifted Pungs',
    chinese: '三色三節高 (Sān Sè Sān Jié Gāo)',
    fan: 8,
    description: 'Three pongs of consecutive numbers, each in a different suit. For example, 1-1-1 Bamboo, 2-2-2 Characters, 3-3-3 Dots.',
    example: '111 Bamboo, 222 Characters, 333 Dots + one other meld + pair.',
    category: 'chinese-mid',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 8,
  },
  'Two Concealed Kongs': {
    english: 'Two Concealed Kongs',
    chinese: '雙暗槓 (Shuāng Àn Gàng)',
    fan: 8,
    description: 'Two of the melds are concealed kongs (four of a kind, not revealed to opponents until the hand is won).',
    category: 'situational',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 8,
  },
  'Last Tile Draw': {
    english: 'Last Tile Draw',
    chinese: '妙手回春 (Miào Shǒu Huí Chūn)',
    fan: 8,
    description: 'Win by self-drawing the very last tile from the wall. "Wonderful hand brings spring back." A dramatic finish.',
    category: 'situational',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 8,
  },
  'Last Tile Claim': {
    english: 'Last Tile Claim',
    chinese: '海底撈月 (Hǎi Dǐ Lāo Yuè)',
    fan: 8,
    description: 'Win by claiming the discard made after the last tile draw from the wall. "Scooping the moon from the bottom of the sea."',
    category: 'situational',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 8,
  },
  'Out with Replacement Tile': {
    english: 'Out with Replacement Tile',
    chinese: '槓上開花 (Gàng Shàng Kāi Huā)',
    fan: 8,
    description: 'Win on the replacement tile drawn after declaring a kong. "Blooming on the kong." The kong gives you an extra draw, and that draw completes your hand.',
    category: 'situational',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 8,
  },
  'Robbing the Kong': {
    english: 'Robbing the Kong',
    chinese: '搶槓 (Qiǎng Gàng)',
    fan: 8,
    description: 'Win by claiming a tile that another player is using to extend a pong into a kong. MCR values this at 8 points (vs. 1 fan in HK rules).',
    category: 'situational',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 8,
  },
  'Chicken Hand': {
    english: 'Chicken Hand',
    chinese: '雞和 (Jī Hé)',
    fan: 8,
    description: 'A winning hand worth zero pattern points. In MCR, the minimum to win is 8 points, so if your hand has no scoreable patterns, it cannot be declared as a win. Sometimes house rules award 8 points as a consolation.',
    category: 'chinese-low',
    ruleset: ['chinese'],
    mcrPoints: 0,
  },

  // === 6 points ===
  'Mixed Shifted Chows': {
    english: 'Mixed Shifted Chows',
    chinese: '三色三步高 (Sān Sè Sān Bù Gāo)',
    fan: 6,
    description: 'Three chows across three different suits, each shifted up by 1. For example, 1-2-3 Bamboo, 2-3-4 Characters, 3-4-5 Dots.',
    example: '123 Bamboo, 234 Characters, 345 Dots + one other meld + pair.',
    category: 'chinese-low',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 6,
  },
  'All Types': {
    english: 'All Types',
    chinese: '五門齊 (Wǔ Mén Qí)',
    fan: 6,
    description: 'Hand contains tiles from all five types: Bamboo, Characters, Dots, Winds, and Dragons. "All five gates." The most inclusive hand composition.',
    example: '1-2-3 Bamboo, 4-5-6 Characters, 7-8-9 Dots, East x3 + Red x2.',
    category: 'chinese-low',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 6,
  },
  'Melded Hand': {
    english: 'Melded Hand',
    chinese: '全求人 (Quán Qiú Rén)',
    fan: 6,
    description: 'All four melds were formed by claiming other players\' discards (all open/melded), and you win by claiming a discard for the pair. "Begging from everyone." The opposite of concealed play.',
    category: 'chinese-low',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 6,
  },
  'Two Dragon Pungs': {
    english: 'Two Dragon Pungs',
    chinese: '雙箭刻 (Shuāng Jiàn Kè)',
    fan: 6,
    description: 'Pongs of two different Dragon tiles. Worth 6 MCR points total (not counted separately per dragon in MCR).',
    example: 'Red x3, Green x3 + two other melds + pair.',
    category: 'chinese-low',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 6,
  },

  // === 4 points ===
  'Outside Hand': {
    english: 'Outside Hand',
    chinese: '全帶幺 (Quán Dài Yāo)',
    fan: 4,
    description: 'Every meld and the pair includes at least one terminal (1 or 9) or honor tile. Chows must be 123 or 789; pongs must be of terminals or honors; the pair is a terminal or honor.',
    example: '1-2-3 Bamboo, 7-8-9 Characters, East x3, 9-9-9 Dots + 1-1 Bamboo.',
    category: 'chinese-low',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 4,
  },
  'Fully Concealed Hand': {
    english: 'Fully Concealed Hand',
    chinese: '不求人 (Bù Qiú Rén)',
    fan: 4,
    description: 'Win with a fully concealed hand AND by self-draw. "Not asking anyone." Never claimed a discard, and completed the hand yourself. Combines concealment with self-draw.',
    category: 'chinese-low',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 4,
  },
  'Two Melded Kongs': {
    english: 'Two Melded Kongs',
    chinese: '雙明槓 (Shuāng Míng Gàng)',
    fan: 4,
    description: 'Two of the melds are melded (open) kongs — four of a kind formed by adding to an exposed pong.',
    category: 'situational',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 4,
  },
  'Last of its Kind': {
    english: 'Last of its Kind',
    chinese: '和絕張 (Hé Jué Zhāng)',
    fan: 4,
    description: 'Win on the last available copy of the winning tile — all other three copies are already visible (discarded, in kongs, etc.). "Winning on the absolute last tile."',
    category: 'situational',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 4,
  },

  // === 2 points ===
  'Double Pung': {
    english: 'Double Pung',
    chinese: '雙同刻 (Shuāng Tóng Kè)',
    fan: 2,
    description: 'Two pongs of the same number in different suits. For example, 3-3-3 Bamboo and 3-3-3 Characters.',
    example: '333 Bamboo, 333 Characters + two other melds + pair.',
    category: 'chinese-low',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 2,
  },
  'Two Concealed Pungs': {
    english: 'Two Concealed Pungs',
    chinese: '雙暗刻 (Shuāng Àn Kè)',
    fan: 2,
    description: 'Two of the melds are concealed pongs (formed without claiming discards).',
    category: 'chinese-low',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 2,
  },
  'Concealed Kong': {
    english: 'Concealed Kong',
    chinese: '暗槓 (Àn Gàng)',
    fan: 2,
    description: 'One concealed kong (four of a kind, all self-drawn, declared face down).',
    category: 'situational',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 2,
  },
  'All Simples': {
    english: 'All Simples',
    chinese: '斷幺九 (Duàn Yāo Jiǔ)',
    fan: 2,
    description: 'No terminals (1 or 9) and no honor tiles in the entire hand. Only tiles numbered 2 through 8. "Cut off the ones and nines."',
    example: '2-3-4 Bamboo, 3-4-5 Characters, 5-6-7 Dots, 6-6-6 Bamboo + 4-4 Characters.',
    category: 'chinese-low',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 2,
  },

  // === 1 point ===
  'Pure Double Chow': {
    english: 'Pure Double Chow',
    chinese: '一般高 (Yī Bān Gāo)',
    fan: 1,
    description: 'Two identical chows in the same suit. For example, two copies of 2-3-4 Bamboo.',
    example: '2-3-4 x2 in Bamboo + two other melds + pair.',
    category: 'chinese-1pt',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 1,
  },
  'Mixed Double Chow': {
    english: 'Mixed Double Chow',
    chinese: '喜相逢 (Xǐ Xiāng Féng)',
    fan: 1,
    description: 'Two chows of the same numbers in two different suits. For example, 2-3-4 Bamboo and 2-3-4 Characters.',
    example: '234 Bamboo, 234 Characters + two other melds + pair.',
    category: 'chinese-1pt',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 1,
  },
  'Short Straight': {
    english: 'Short Straight',
    chinese: '連六 (Lián Liù)',
    fan: 1,
    description: 'Two chows in the same suit forming a 6-tile consecutive sequence. For example, 1-2-3 and 4-5-6 in Bamboo.',
    example: '123, 456 Bamboo + two other melds + pair.',
    category: 'chinese-1pt',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 1,
  },
  'Two Terminal Chows': {
    english: 'Two Terminal Chows',
    chinese: '老少副 (Lǎo Shào Fù)',
    fan: 1,
    description: '1-2-3 and 7-8-9 in the same suit. The "old and young" chows — one from each end of the suit.',
    example: '123, 789 Bamboo + two other melds + pair.',
    category: 'chinese-1pt',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 1,
  },
  'Pung of Terminals or Honors': {
    english: 'Pung of Terminals or Honors',
    chinese: '幺九刻 (Yāo Jiǔ Kè)',
    fan: 1,
    description: 'A pong of terminal tiles (1 or 9) or honor tiles (any Wind or Dragon). Each such pong scores 1 point independently.',
    example: '1-1-1 Bamboo or East-East-East = 1 point each.',
    category: 'chinese-1pt',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 1,
  },
  'Melded Kong': {
    english: 'Melded Kong',
    chinese: '明槓 (Míng Gàng)',
    fan: 1,
    description: 'One melded (open) kong — four of a kind formed by adding to an exposed pong or by claiming a discard.',
    category: 'situational',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 1,
  },
  'One Voided Suit': {
    english: 'One Voided Suit',
    chinese: '缺一門 (Quē Yī Mén)',
    fan: 1,
    description: 'Missing one entire numbered suit. Your hand uses tiles from only two of the three suits (plus possibly honors).',
    example: 'No Bamboo tiles at all, hand uses Characters, Dots, and/or honors.',
    category: 'chinese-1pt',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 1,
  },
  'No Honor Tiles': {
    english: 'No Honor Tiles',
    chinese: '無字 (Wú Zì)',
    fan: 1,
    description: 'No Wind or Dragon tiles in the hand. All tiles are from the three numbered suits.',
    category: 'chinese-1pt',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 1,
  },
  'Flowers': {
    english: 'Flowers',
    chinese: '花牌 (Huā Pái)',
    fan: 1,
    description: 'Each Flower or Season bonus tile matching your seat earns 1 point. Not tracked in this trainer.',
    category: 'situational',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 1,
  },

  // === Wait patterns (1 point each in MCR) ===
  'Edge Wait': {
    english: 'Edge Wait',
    chinese: '邊張 (Biān Zhāng)',
    fan: 1,
    description: 'Waiting on the edge of a sequence: waiting on 3 to complete 1-2-3, or waiting on 7 to complete 7-8-9. Only one tile can complete the sequence from that end.',
    example: 'Holding 1-2, waiting on 3 (or holding 8-9, waiting on 7).',
    category: 'chinese-1pt',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 1,
  },
  'Closed Wait': {
    english: 'Closed Wait',
    chinese: '嵌張 (Qiàn Zhāng)',
    fan: 1,
    description: 'Waiting on the middle tile of a sequence. For example, holding 4 and 6, waiting on 5 to complete 4-5-6. Also called "inserted tile" wait.',
    example: 'Holding 4-6, waiting on 5.',
    category: 'chinese-1pt',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 1,
  },
  'Single Wait': {
    english: 'Single Wait',
    chinese: '單釣將 (Dān Diào Jiàng)',
    fan: 1,
    description: 'Waiting on a single tile to complete the pair. All four melds are already complete; you just need the pair tile.',
    example: 'Four complete melds, waiting on one specific tile for the pair.',
    category: 'chinese-1pt',
    ruleset: ['chinese', 'blended'],
    mcrPoints: 1,
  },
};

export function getAllGlossaryEntries(rulesetFilter?: string): GlossaryEntry[] {
  const entries = Object.values(GLOSSARY);

  const filtered = rulesetFilter
    ? entries.filter(e => e.ruleset.includes(rulesetFilter as 'hk' | 'chinese' | 'blended'))
    : entries;

  const categoryOrder: Record<string, number> = {
    basic: 0,
    honor: 1,
    hand: 2,
    limit: 3,
    'chinese-high': 4,
    'chinese-mid': 5,
    'chinese-low': 6,
    'chinese-1pt': 7,
    situational: 8,
  };
  filtered.sort((a, b) => {
    const catDiff = (categoryOrder[a.category] ?? 9) - (categoryOrder[b.category] ?? 9);
    if (catDiff !== 0) return catDiff;
    return b.fan - a.fan; // Higher value first within category
  });
  return filtered;
}
